project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - href: index.qmd
        text: "Hands-on Exercise"
        menu:
          - text:"Hands-on 1"
          #href:"Hands-on_Ex/Hands-on_Ex01/Hands_Ex01.html"
     
    right:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

